version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myclinic-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "8081:3000"
    networks:
      - myclinic-network

networks:
  myclinic-network:
    driver: bridge
