services:
  # Next.js Frontend (apenas)
  frontend:
    image: ghcr.io/CSFDuarte/myclinic-app-frontend:latest
    container_name: myclinic-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "8081:3000"
    networks:
      - myclinic-network

networks:
  myclinic-network:
    driver: bridge

volumes:
  # Volume para persistir dados do frontend se necessário
  frontend_data:
